version: "2.3"
services:
  queue:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  flower:
    image: mher/flower:0.9.5
    ports:
      - "5555:5555"
    environment:
      - FLOWER_BASIC_AUTH=admin:ninja-password
    command:
      - "--broker=amqp://guest@queue:5672//"

  worker:
    build: ./
    volumes:
      - ./:/usr/src/app
    # environment:
    #   - QUEUE_DOMAIN=192.168.1.2:5672
    command: celery -A task worker --loglevel=INFO -c 1
